-- SELECTING PATH FOR DATABASE AND SCHEMA

SET SEARCH_PATH TO cardekho, CARDEKHO;

-- CREATING SCHEMA

CREATE SCHEMA CARDEKHO;


--CREATING TABLE TO IMPORT FILE

CREATE TABLE CAR(
brand VARCHAR(40),
model  VARCHAR(30),
vehicle_age VARCHAR(20),
km_driven VARCHAR(30),
seller_type VARCHAR(30),
fuel_type VARCHAR(50),
transmission_type VARCHAR(30),
mileage FLOAT(20),
engine VARCHAR(30),
max_power VARCHAR(30),
seats NUMERIC(20),
selling_price VARCHAR(30),
Actual_Price VARCHAR(30),
Fixed_Profit VARCHAR(30)
);


-- CHECKING DATA SUCESSFULLY IMPORTED

SELECT * FROM CAR;


--ANALYZING WHAT EACH COLUMN CONTAINS

SELECT DISTINCT BRAND FROM CAR
ORDER BY BRAND;

SELECT DISTINCT MODEL FROM CAR
ORDER BY MODEL;

SELECT DISTINCT VEHICLE_AGE FROM CAR
ORDER BY VEHICLE_AGE;

SELECT DISTINCT KM_DRIVEN FROM CAR
ORDER BY KM_DRIVEN;

SELECT DISTINCT SELLER_TYPE FROM CAR
ORDER BY SELLER_TYPE;

SELECT DISTINCT FUEL_TYPE FROM CAR
ORDER BY FUEL_TYPE;

SELECT DISTINCT TRANSMISSION_TYPE FROM CAR
ORDER BY TRANSMISSION_TYPE;

SELECT DISTINCT ENGINE FROM CAR
ORDER BY ENGINE;

SELECT DISTINCT MAX_POWER FROM CAR
ORDER BY MAX_POWER;

SELECT DISTINCT SELLING_PRICE FROM CAR
ORDER BY SELLING_PRICE;


--CREATING TABLE AS A BACKUP

CREATE TABLE CAR AS TABLE PO;

-- CLEANING AND UPDATING FIRST COLUMN BRAND USING CASE STATEMENT

UPDATE CAR
SET BRAND = 
CASE
   WHEN BRAND LIKE '%Maru%' then 'Maruti'
   WHEN BRAND LIKE '%Ford%' then 'Ford'
   WHEN BRAND LIKE '%Mahin%' then 'Mahindra'
   WHEN BRAND LIKE '%Hyun%' then 'Hyundai'
   WHEN BRAND LIKE '%Hon%' then 'Honda'
   WHEN BRAND LIKE '%Volk%' then 'Volkswagen'
   WHEN BRAND LIKE '%BMW%' then 'BMW'
   WHEN BRAND LIKE '%Volvo%' then 'Volvo'
   WHEN BRAND LIKE '%Toyo%' then 'Toyota'
   WHEN BRAND LIKE '%Pors%' then 'Porsche'
   WHEN BRAND LIKE '%Tata%' then 'Tata'
   WHEN BRAND LIKE '%Rena%' then 'Renault'
   WHEN BRAND LIKE '%Dats%' then 'Datsun'
   WHEN BRAND LIKE '%Skoda%' then 'Skoda'
ELSE CAST(BRAND AS VARCHAR)
END 


-- CLEANING AND UPDATING SECOND COLUMN MODEL USING CASE STATEMENT 

Select distinct model from car
order by model;

UPDATE CAR
SET MODEL = 
CASE
   WHEN Model LIKE '%City%' then 'City'
   WHEN Model LIKE '%Polo%' then 'Polo'
   WHEN Model LIKE '%KWI%' then 'Kwid'
   WHEN Model LIKE '%Duster%' then 'Duster'
   WHEN Model LIKE '%Balen%' then 'Baleno'
   WHEN Model LIKE '%Cret%' then 'Creta'
   WHEN Model LIKE '%Fortu%' then 'Fortuner'
   WHEN Model LIKE '%Grand%' then 'Grand'
   WHEN Model LIKE '%Hexa%' then 'Hexa'
   WHEN Model LIKE '%i20%' then 'i20'
   WHEN Model LIKE '%Rove%' then 'Rover'
   WHEN Model LIKE '%Scorpio%' then 'Scorpio'
   WHEN Model LIKE '%Tiago%' then 'Tiago'
   WHEN Model LIKE '%Vento%' then 'Vento'
   WHEN Model LIKE '%Verna%' then 'Verna'
   WHEN Model LIKE '%Vitara%' then 'Viata'
   WHEN Model LIKE '%Wagon R%' then 'Wagon R'
   WHEN Model LIKE '%WR-V%' then 'WR-V'
   WHEN Model LIKE '%XUV500%' then 'XUV500'
   WHEN Model LIKE '%Alto%' then 'Alto'
   WHEN Model LIKE '%Swift_Dzire%' then 'Dzire'
   WHEN Model LIKE '%Swift%' then 'Swift'
   WHEN MODEL = 'ajajaxsda' then 'Aura'
   ELSE CAST(Model AS VARCHAR)
END 



-- FILLING MISSING VALUES OF BRAND USING UPDATE STATEMENT FOR COLUMN BRAND AND CAN BE DONE USING SELF JOIN AS WELL

SELECT DISTINCT BRAND FROM CAR
ORDER BY BRAND

select * from car 
where brand in ('N/A' , 'N/a','UNKNOWN' )

select * from car 
where brand LIKE 's'

select * from car 
where brand IS 'null'

BEGIN;
UPDATE CAR SET BRAND = 'Maruti'WHERE MODEL IN ('Wagon R','Swift Dzire','s');
UPDATE CAR SET BRAND = 'Renault' WHERE MODEL IN ('Duster');
UPDATE CAR SET BRAND = 'Mahindra' WHERE MODEL IN ('Scorpio');
UPDATE CAR SET BRAND = 'Hyundai' WHERE MODEL IN ('i20');
UPDATE CAR SET BRAND = 'Honda' WHERE MODEL IN ('City');
UPDATE CAR SET BRAND = 'Honda' WHERE MODEL IN ('Jazz');
UPDATE CAR SET BRAND = 'Hyundai' WHERE MODEL IN ('Grand');
UPDATE CAR SET BRAND = 'Maruti' WHERE BRAND LIKE 's' AND MODEL = 'Celerio';
COMMIT;


-- FILLING MISSING VALUE INTO THE COLUMN MODEL

UPDATE CAR 
SET MODEL = null                                                     -- CHANGING WRONG DATA AS NULL VALUE SO THAT MISSING VALUE 
where model in ('N/a','NA','Unknown','UnKNown','UNKNOWN')                    --CAN BE AUTO FILLING USING SELF JOIN.

UPDATE car c1
SET model = c2.model
FROM car c2
WHERE c1.engine = c2.engine
AND c1.max_power = c2.max_power                                      -- USING SELF-JOIN TO FIND MISSING VALUE. 
AND c1.model IS NULL
AND c2.model IS NOT NULL;

BEGIN;
UPDATE CAR SET MODEL = 'Rover' WHERE BRAND = 'Land Rover' AND VEHICLE_AGE = '3';
UPDATE CAR SET MODEL = 'Bolero' WHERE BRAND = 'Mahindra'AND VEHICLE_AGE ='13' AND KM_DRIVEN = '220000'             -- UPDATING LEFTOVER MODEL MANUALLY
COMMIT;

SELECT  BRAND, MODEL FROM CAR
GROUP BY BRAND , MODEL                                               -- FOR ANALYZING PURPOSE.  
ORDER BY BRAND 

--CLEANING AND UPDATING COLUMN VEHICLE_AGE AND KM_DRIVEN


UPDATE CAR
SET KM_DRIVEN = REGEXP_REPLACE(KM_DRIVEN, '[^0-9.]','','g')         -- REPLACING UNWANTED CHARACTER AGAINST NUMBER IN A COLUMN.



UPDATE CAR
SET VEHICLE_AGE = REGEXP_REPLACE(VEHICLE_AGE, '[^0-9.]', '', 'g')   -- REPLACING UNWANTED CHARACTER AGAINST NUMBER IN A COLUMN. 



--CHANGING DATA TYPE FOR COLUMN VEHICLE_AGE

ALTER TABLE CAR
ALTER COLUMN VEHICLE_AGE TYPE NUMERIC                               --  THIS FUCTION WILL CHANGE DATA TYPE FOR A COLUMN. 
USING VEHICLE_AGE::NUMERIC

ALTER TABLE CAR
ALTER COLUMN KM_DRIVEN TYPE NUMERIC
USING KM_DRIVEN::NUMERIC

UPDATE CAR
SET VEHICLE_AGE = ABS(VEHICLE_AGE)                                  -- THIS WILL REMOVE ANY NEGATIVE SIGN AGAINST ANY NUMBER IN A COLUMN. 

UPDATE CAR
SET KM_DRIVEN = ABS(KM_DRIVEN) 

--CLEANING AND UPDATING COLUMN SELLER_TYPE, FUEL_TYPE, TRANSMISSION_TYPE, MILEAGE USING CASE FUNCTION

UPDATE CAR
SET SELLER_TYPE = 
CASE
 WHEN SELLER_TYPE LIKE '%Trustmark_D' THEN 'Trustmark'
 WHEN SELLER_TYPE LIKE '%De%' THEN 'Dealer'
 WHEN SELLER_TYPE LIKE '%DL%' THEN 'Dealer'
 WHEN SELLER_TYPE LIKE '%In%' THEN 'Individual'
 WHEN SELLER_TYPE LIKE '%IN%' THEN 'Individual'
 WHEN SELLER_TYPE LIKE '%Trustmark_D' THEN 'Trustmark-Dealer'
 ELSE CAST(SELLER_TYPE AS VARCHAR)
END;

UPDATE CAR 
SET FUEL_TYPE = 
CASE 
 WHEN FUEL_TYPE LIKE '%D%' THEN 'Diesel'
 WHEN FUEL_TYPE LIKE '%d%' THEN 'Diesel'
 WHEN FUEL_TYPE LIKE '%P%' THEN 'Petrol'
 WHEN FUEL_TYPE LIKE '%p%' THEN 'Petrol'
 ELSE CAST(FUEL_TYPE AS VARCHAR)
END;


UPDATE CAR 
SET TRANSMISSION_TYPE = 
CASE 
 WHEN TRANSMISSION_TYPE LIKE '%Man%' THEN 'Manual'
 WHEN TRANSMISSION_TYPE LIKE '%man%' THEN 'Manual'
 WHEN TRANSMISSION_TYPE LIKE '%Auto%' THEN 'Automatic'
 WHEN TRANSMISSION_TYPE LIKE '%auto%' THEN 'Automatic'
 WHEN TRANSMISSION_TYPE LIKE '%amt%' THEN 'Automatic'
 WHEN TRANSMISSION_TYPE ='mn' THEN 'Manual'
 WHEN TRANSMISSION_TYPE = 'Ma' THEN 'Manual'
 ELSE CAST(TRANSMISSION_TYPE AS VARCHAR)
END; 


UPDATE CAR
SET MILEAGE = ABS(MILEAGE)                                        -- THIS WILL REMOVE ANY NEGATIVE SIGN AGAINST ANY NUMBER. 




-- FILLING MISSING VALUE OF COLUMN ENGINE AND CHANGING DATA TYPE

UPDATE CAR 
SET ENGINE = NULL                                                 -- CHANGING WRONG DATA AS NULL VALUE SO THAT MISSING VALUE
WHERE ENGINE IN ('nan', 'NA', 'UNKNOWN', '0')                                  -- CAN BE AUTO FILLING USING SELF JOIN.

SELECT DISTINCT ENGINE FROM CAR 

UPDATE CAR C1
SET ENGINE = C2.ENGINE
FROM CAR C2
WHERE C1.MODEL = C2.MODEL
AND C1.MAX_POWER = C2.MAX_POWER                                   -- USING SELF-JOIN TO FIND MISSING VALUE. 
AND C1.ENGINE IS NULL
AND C2.ENGINE IS NOT NULL

ALTER TABLE CAR
ALTER COLUMN ENGINE TYPE NUMERIC                                  -- CHANGING DATA TYPE TO NUMERIC.
USING ENGINE::NUMERIC


-- FILLING MISSING VALUE OF COLUMN ENGINE AND CHANGING DATA TYPE

SELECT * FROM CAR
WHERE MAX_POWER IS NULL

UPDATE CAR 
SET MAX_POWER = NULL                                               -- CHANGING WRONG DATA AS NULL VALUE SO THAT MISSING VALUE 
WHERE MAX_POWER IN ('nan', 'NA', 'Unknown')                               --CAN BE AUTO FILLING USING SELF JOIN.


UPDATE CAR C1
SET MAX_POWER = C2.MAX_POWER
FROM CAR C2
WHERE C1.MODEL = C2.MODEL                                          -- USING SELF-JOIN TO FIND MISSING VALUE.
AND C1.ENGINE = C2.ENGINE
AND C1.MAX_POWER IS NULL
AND C2.MAX_POWER IS NOT NULL


ALTER TABLE CAR 
ALTER COLUMN MAX_POWER TYPE FLOAT                                  -- CHANGING DATA TYPE TO FLOAT.
USING MAX_POWER::FLOAT




-- FILLING MISSING VALUE OF COLUMN SELLING , ACTUAL, FIXED PROFIT AND CHANGING DATA TYPE


SELECT DISTINCT SELLING_PRICE FROM CAR

UPDATE CAR 
SET SELLING_PRICE = '0'
WHERE SELLING_PRICE IN ('nan', 'n?a', 'unknown', 'NAN', 'n/A', 'NA','\')    -- CHANGING WRONG DATA AS 0 SO THAT LATER WE CAN CONVERT 
                                                                                    -- COLUMN INTO NUMERIC DATA TYPE TO PERFORM ARITHMETIC FUCTION.

UPDATE CAR 
SET SELLING_PRICE = COALESCE(SELLING_PRICE, '0')                            -- CHANGING NULL VALUE AS 0 SO THAT LATER WE CAN CONVERT COLUMN INTO NUMERIC DATA TYPE.


UPDATE CAR 
SET SELLING_PRICE = REGEXP_REPLACE(SELLING_PRICE,'[^0-9.]','', 'g')         -- REMOVING UNWANTED CHARACTER AGAINST NUMERIC VALUE.


ALTER TABLE CAR
ALTER COLUMN SELLING_PRICE TYPE NUMERIC                                     -- CHANGING DATA TYPE TO NUMERIC. 
USING SELLING_PRICE::NUMERIC


-- FOR ACTUAL PRICE 

SELECT DISTINCT ACTUAL_PRICE FROM CAR 

UPDATE CAR 
SET ACTUAL_PRICE = '0'
WHERE ACTUAL_PRICE IN ('nan', 'n?a', 'unknown', 'NAN', 'n/A', 'NA','\','UNKNOWN')   

UPDATE CAR 
SET ACTUAL_PRICE = REGEXP_REPLACE(ACTUAL_PRICE,'[^0-9.]','', 'g')

UPDATE CAR 
SET ACTUAL_PRICE = COALESCE(ACTUAL_PRICE, '0')                              -- ALL FUNCTION SAME AS ABOVE COLUMN.

ALTER TABLE CAR
ALTER COLUMN ACTUAL_PRICE TYPE NUMERIC
USING ACTUAL_PRICE::NUMERIC

-- FOR FIXED PROFIT 

SELECT DISTINCT FIXED_PROFIT FROM CAR
ORDER BY FIXED_PROFIT

UPDATE CAR 
SET FIXED_PROFIT = '0'
WHERE FIXED_PROFIT IN ( 'iiiii', 'n/A', 'N/A', 'nan', 'NAN', 'nil','UNKNOWN')

UPDATE CAR 
SET FIXED_PROFIT = COALESCE(FIXED_PROFIT, '0')

UPDATE CAR 
SET FIXED_PROFIT = REGEXP_REPLACE(FIXED_PROFIT,'[^0-9.]','', 'g')          -- ALL FUNCTION SAME AS ABOVE COLUMN.

ALTER TABLE CAR
ALTER COLUMN FIXED_PROFIT TYPE NUMERIC
USING FIXED_PROFIT::NUMERIC



-- FILLING MISSSING VALUE

UPDATE CAR,
SET SELLING_PRICE = 
CASE
 WHEN SELLING_PRICE = '0' THEN ACTUAL_PRICE + FIXED_PROFIT                -- USING CASE FUCTION COMBINED WITH ARITHMETIC FUNTION TO FIND MISSING VALUES. 
 ELSE CAST(SELLING_PRICE AS NUMERIC)
 END

UPDATE CAR
SET ACTUAL_PRICE = 
CASE
WHEN ACTUAL_PRICE = '0' THEN SELLING_PRICE - FIXED_PROFIT                 -- USING CASE FUCTION COMBINED WITH ARITHMETIC FUNTION TO FIND MISSING VALUES.
ELSE CAST(ACTUAL_PRICE AS NUMERIC)
END

UPDATE CAR
SET FIXED_PROFIT = 
CASE
WHEN FIXED_PROFIT = '0' THEN  SELLING_PRICE - ACTUAL_PRICE                -- USING CASE FUCTION COMBINED WITH ARITHMETIC FUNTION TO FIND MISSING VALUES.
ELSE CAST(FIXED_PROFIT AS NUMERIC)
END

-- REMOVING DUPLICATE ROWS 





WITH DUP_CAR AS
(
    SELECT 
        ctid,
        ROW_NUMBER() OVER
        (
            PARTITION BY 
                BRAND,
                MODEL,
                VEHICLE_AGE,
                KM_DRIVEN,
                SELLER_TYPE,
                FUEL_TYPE,
                TRANSMISSION_TYPE,
                ENGINE,
                MILEAGE,
                SELLING_PRICE
            ORDER BY ctid
        ) AS RN
    FROM CAR
)

DELETE FROM CAR
WHERE ctid IN
(
    SELECT ctid
    FROM DUP_CAR
    WHERE RN > 1
);














